## Juntando as bases

In [1]:
#Importações
import pandas as pd
import re

from Apoio.config import (
    DADOS_2005_2014,
    DADOS_2015_2019,
    DADOS_2020,
    DADOS_2021,
    DADOS_2022,
    DADOS_2023,
    DADOS_2024,
    DADOS_CONSOLIDADOS,
)

#### Concatenando os dataframes

In [2]:
df_2005_2014 = pd.read_csv(DADOS_2005_2014)
df_2015_2019 = pd.read_csv(DADOS_2015_2019)
df_2020 = pd.read_csv(DADOS_2020)
df_2021 = pd.read_csv(DADOS_2021)
df_2022 = pd.read_csv(DADOS_2022)
df_2023 = pd.read_csv(DADOS_2023, encoding="latin")
df_2024 = pd.read_csv(DADOS_2024, encoding="latin")

In [3]:
df_2005_2014.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2005,Acura,1.7EL,Compact,1.7,4,A4,X,9.2,7.2,8.3,34,191,NaN,NaN
1,2005,Acura,1.7EL,Compact,1.7,4,M5,X,9.1,7.3,8.3,34,191,NaN,NaN
2,2005,Acura,MDX AWD,Sport utility vehicle,3.5,6,A5,Z,15.9,11.1,13.7,21,315,NaN,NaN
3,2005,Acura,NSX,Two-seater,3.0,6,AS4,Z,15.1,10.5,13.0,22,299,NaN,NaN
4,2005,Acura,NSX,Two-seater,3.2,6,M6,Z,15.1,10.5,13.0,22,299,NaN,NaN

In [4]:
df_2015_2019.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2015,Acura,ILX,Compact,2.0,4,AS5,Z,9.7,6.7,8.3,34,191,NaN,NaN
1,2015,Acura,ILX,Compact,2.4,4,M6,Z,10.8,7.4,9.3,30,214,NaN,NaN
2,2015,Acura,ILX Hybrid,Compact,1.5,4,AV7,Z,6.0,6.1,6.1,46,140,NaN,NaN
3,2015,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS6,Z,12.7,9.1,11.1,25,255,NaN,NaN
4,2015,Acura,RDX AWD,Sport utility vehicle: Small,3.5,6,AS6,Z,12.1,8.7,10.6,27,244,NaN,NaN

In [5]:
df_2020.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2020,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,199,6,3
1,2020,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS9,Z,12.3,9.2,10.9,26,254,4,3
2,2020,Acura,MDX SH-AWD A-SPEC,Sport utility vehicle: Small,3.5,6,AS9,Z,12.2,9.5,11.0,26,258,4,3
3,2020,Acura,MDX Hybrid AWD,Sport utility vehicle: Small,3.0,6,AM7,Z,9.1,9.0,9.0,31,210,5,3
4,2020,Acura,NSX,Two-seater,3.5,6,AM9,Z,11.1,10.8,11.0,26,261,4,3

In [6]:
df_2021.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2021,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,199,6,3
1,2021,Acura,NSX,Two-seater,3.5,6,AM9,Z,11.1,10.8,11.0,26,256,4,3
2,2021,Acura,RDX SH-AWD,Sport utility vehicle: Small,2.0,4,AS10,Z,11.0,8.6,9.9,29,232,5,6
3,2021,Acura,RDX SH-AWD A-SPEC,Sport utility vehicle: Small,2.0,4,AS10,Z,11.3,9.1,10.3,27,242,5,6
4,2021,Acura,TLX SH-AWD,Compact,2.0,4,AS10,Z,11.2,8.0,9.8,29,230,5,7

In [7]:
df_2022.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2022,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,200,6,3
1,2022,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,5
2,2022,Acura,MDX Type S,Sport utility vehicle: Standard,3.0,6,AS10,Z,13.8,11.2,12.4,23,291,4,5
3,2022,Acura,NSX,Two-seater,3.5,6,AM9,Z,11.1,10.8,11.0,26,256,5,3
4,2022,Acura,RDX SH-AWD,Sport utility vehicle: Small,2.0,4,AS10,Z,11.0,8.6,9.9,29,232,5,6

In [8]:
df_2023.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2023,Acura,Integra,Full-size,1.5,4,AV7,Z,7.9,6.3,7.2,39,167,6,7
1,2023,Acura,Integra A-SPEC,Full-size,1.5,4,AV7,Z,8.1,6.5,7.4,38,172,6,7
2,2023,Acura,Integra A-SPEC,Full-size,1.5,4,M6,Z,8.9,6.5,7.8,36,181,6,6
3,2023,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,5
4,2023,Acura,MDX SH-AWD Type S,Sport utility vehicle: Standard,3.0,6,AS10,Z,13.8,11.2,12.4,23,291,4,5

In [9]:
df_2024.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2024,Acura,Integra A-SPEC,Full-size,1.5,4,AV7,Z,8.1,6.5,7.4,38,172,6,7
1,2024,Acura,Integra A-SPEC,Full-size,1.5,4,M6,Z,8.9,6.5,7.8,36,181,6,6
2,2024,Acura,Integra Type S,Full-size,2.0,4,M6,Z,11.1,8.3,9.9,29,230,5,6
3,2024,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,5
4,2024,Acura,MDX SH-AWD Type S,Sport utility vehicle: Standard,3.0,6,AS10,Z,13.8,11.2,12.4,23,291,4,5

In [10]:
df = pd.concat([df_2005_2014, df_2015_2019, df_2020, df_2021, df_2022, df_2023, df_2024])

df = df.reset_index(drop=True)

#### Checagens básicas

In [11]:
df.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2005,Acura,1.7EL,Compact,1.7,4,A4,X,9.2,7.2,8.3,34,191,NaN,NaN
1,2005,Acura,1.7EL,Compact,1.7,4,M5,X,9.1,7.3,8.3,34,191,NaN,NaN
2,2005,Acura,MDX AWD,Sport utility vehicle,3.5,6,A5,Z,15.9,11.1,13.7,21,315,NaN,NaN
3,2005,Acura,NSX,Two-seater,3.0,6,AS4,Z,15.1,10.5,13.0,22,299,NaN,NaN
4,2005,Acura,NSX,Two-seater,3.2,6,M6,Z,15.1,10.5,13.0,22,299,NaN,NaN

In [12]:
df.tail()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
20516,2024,Volvo,V60 CC B5 AWD,Station wagon: Small,2.0,4,AS8,Z,10.0,7.5,8.9,32,207,5.0,5.0
20517,2024,Volvo,V90 CC B6 AWD,Station wagon: Mid-size,2.0,4,AS8,Z,10.7,8.1,9.5,30,223,5.0,7.0
20518,2024,Volvo,XC40 B5 AWD,Sport utility vehicle: Small,2.0,4,AS8,Z,9.9,7.8,9.0,31,210,5.0,5.0
20519,2024,Volvo,XC60 B5 AWD,Sport utility vehicle: Small,2.0,4,AS8,Z,10.6,8.3,9.6,29,226,5.0,5.0
20520,2024,Volvo,XC90 B6 AWD,Sport utility vehicle: Standard,2.0,4,AS8,Z,10.9,8.6,9.8,29,230,5.0,7.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20521 entries, 0 to 20520
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model year            20521 non-null  int64
 1   Make                  20521 non-null  object
 2   Model                 20521 non-null  object
 3   Vehicle class         20521 non-null  object
 4   Engine size (L)       20521 non-null  float64
 5   Cylinders             20521 non-null  int64
 6   Transmission          20521 non-null  object
 7   Fuel type             20521 non-null  object
 8   City (L/100 km)       20521 non-null  float64
 9   Highway (L/100 km)    20521 non-null  float64
 10  Combined (L/100 km)   20521 non-null  float64
 11  Combined (mpg)        20521 non-null  int64
 12  CO2 emissions (g/km)  20521 non-null  int64
 13  CO2 rating            8832 non-null   float64
 14  Smog rating           7726 non-null   float64
dtypes: float64(6), int64(4), object(5)
memory usage: 2.3+ MB

In [14]:
with pd.option_context("display.float_format", "{:.2f}".format):
    display(df.describe())

,Model year,Engine size (L),Cylinders,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
count,20521.00,20521.00,20521.00,20521.00,20521.00,20521.00,20521.00,20521.00,8832.00,7726.00
mean,2014.24,3.34,5.83,13.44,9.72,11.76,25.74,266.81,4.63,4.82
std,5.59,1.35,1.87,3.78,2.52,3.18,7.02,63.51,1.58,1.79
min,2005.00,0.80,2.00,4.00,3.90,4.00,11.00,94.00,1.00,1.00
25%,2009.00,2.20,4.00,10.80,8.00,9.60,21.00,221.00,4.00,3.00
50%,2014.00,3.00,6.00,13.00,9.30,11.30,25.00,262.00,5.00,5.00
75%,2019.00,4.00,8.00,15.50,11.00,13.40,29.00,304.00,5.00,6.00
max,2024.00,8.40,16.00,30.70,22.10,26.10,71.00,608.00,10.00,8.00

In [15]:
df.describe(exclude="number")

             Make    Model Vehicle class Transmission Fuel type
count       20521    20521         20521        20521     20521
unique         48     3522            17           29         5
top     Chevrolet  Mustang      Mid-size          AS6         X
freq         1884       96          2736         2876     10179

#### Traduzindo os nomes das colunas

| Original               | Tradução                    |
| ---------------------- | --------------------------- |
| `model year`           | `ano_modelo`                |
| `make`                 | `marca`                     |
| `model`                | `modelo`                    |
| `vehicle class`        | `classe_veiculo`            |
| `engine size (l)`      | `tamanho_motor_l`           |
| `cylinders`            | `cilindros`                 |
| `transmission`         | `transmissao`               |
| `fuel type`            | `tipo_combustivel`          |
| `city (l/100 km)`      | `consumo_cidade_l_100km`    |
| `highway (l/100 km)`   | `consumo_estrada_l_100km`   |
| `combined (l/100 km)`  | `consumo_combinado_l_100km` |
| `combined (mpg)`       | `consumo_combinado_mpg`     |
| `co2 emissions (g/km)` | `emissoes_co2_g_km`         |
| `co2 rating`           | `classificacao_co2`         |
| `smog rating`          | `classificacao_smog`        |

In [16]:
df.columns = [
    'ano_modelo',
    'marca',
    'modelo',
    'classe_veiculo',
    'tamanho_motor_l',
    'cilindros',
    'transmissao',
    'tipo_combustivel',
    'consumo_cidade_l_100km',
    'consumo_estrada_l_100km',
    'consumo_combinado_l_100km',
    'consumo_combinado_mpg',
    'emissoes_co2_g_km',
    'classificacao_co2',
    'classificacao_smog'
]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20521 entries, 0 to 20520
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano_modelo                 20521 non-null  int64
 1   marca                      20521 non-null  object
 2   modelo                     20521 non-null  object
 3   classe_veiculo             20521 non-null  object
 4   tamanho_motor_l            20521 non-null  float64
 5   cilindros                  20521 non-null  int64
 6   transmissao                20521 non-null  object
 7   tipo_combustivel           20521 non-null  object
 8   consumo_cidade_l_100km     20521 non-null  float64
 9   consumo_estrada_l_100km    20521 non-null  float64
 10  consumo_combinado_l_100km  20521 non-null  float64
 11  consumo_combinado_mpg      20521 non-null  int64
 12  emissoes_co2_g_km          20521 non-null  int64
 13  classificacao_co2          8832 non-null   float64
 14  classificacao_smog         7726 non-null   float64
dtypes: float64(6), int64(4), object(5)
memory usage: 2.3+ MB

#### Exportando a base

In [18]:
df.to_parquet(DADOS_CONSOLIDADOS, index=False)